# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box       = 'jayunit100/centos7'
  config.vm.hostname  = 'metal-cell.localdomain'

  config.vm.synced_folder "../../../saasbase-deployment", "/saasbase-deployment"
  config.vm.synced_folder "../../", "/metal-cell"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "8192", "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    vb.customize ["modifyvm", :id, "--natnet1", "10.255.255.224/27"]
    vb.customize ["modifyvm", :id, "--hpet", "on"]
  end

  # all saasbase services are using the following IP:
  config.vm.network "private_network" , ip: "10.255.255.2", netmask: "255.255.255.252"

  if not ENV['PROVISION_ENABLED'].nil?
    config.vm.provision "shell",
        inline: "
                 set -xe
                 sh /saasbase-deployment/saasbase_installer -q -d /saasbase-deployment run-puppet /saasbase-deployment/puppet/clusters/quickstart-1
                "
    config.vm.provision "shell",
        inline: "
                 set -xe
                 sh /saasbase-deployment/puppet/clusters/quickstart-1/bootstrap.sh --reset --force
                "
  end
end
